import type { Express } from "express";
import { authenticate } from "./core/security/auth.middleware.js";
import { requireActiveSubscription } from "./core/security/subscription.middleware.js";
import { accountsRouter } from "./modules/accounts/accounts.routes.js";
import { activityRouter } from "./modules/activity/activity.routes.js";
import { authRouter } from "./modules/auth/auth.routes.js";
import { dashboardRouter } from "./modules/dashboard/dashboard.routes.js";
import { depositDelegatesRouter } from "./modules/deposit-delegates/deposit-delegates.routes.js";
import { depositsRouter } from "./modules/deposits/deposits.routes.js";
import { duesRouter } from "./modules/dues/dues.routes.js";
import { expensesRouter } from "./modules/expenses/expenses.routes.js";
import { expenseCategoriesRouter } from "./modules/expense-categories/expense-categories.routes.js";
import { incomesRouter } from "./modules/incomes/incomes.routes.js";
import { inventoryCategoriesRouter } from "./modules/inventory-categories/inventory-categories.routes.js";
import { inventoryRouter } from "./modules/inventory/inventory.routes.js";
import { purchasesRouter } from "./modules/purchases/purchases.routes.js";
import { salesRouter } from "./modules/sales/sales.routes.js";
import { vendorsRouter } from "./modules/vendors/vendors.routes.js";
import { membersRouter } from "./modules/members/members.routes.js";
import { memberDocumentsRouter } from "./modules/member-documents/member-documents.routes.js";
import { membershipsRouter } from "./modules/memberships/memberships.routes.js";
import { penaltiesRouter } from "./modules/penalties/penalties.routes.js";
import { invitationsRouter, projectsRouter } from "./modules/projects/projects.routes.js";
import { recurringSchedulesRouter } from "./modules/recurring-schedules/recurring-schedules.routes.js";
import { receiptsRouter } from "./modules/receipts/receipts.routes.js";
import { schedulesRouter } from "./modules/schedules/schedules.routes.js";
import { subscriptionRouter } from "./modules/subscription/subscription.routes.js";
import { tenantsRouter } from "./modules/tenants/tenants.routes.js";
import { transfersRouter } from "./modules/transfers/transfers.routes.js";
import { uploadsRouter } from "./modules/uploads/uploads.routes.js";

export function registerRoutes(app: Express) {
  app.use("/v1/tenants", tenantsRouter);
  app.use("/v1/auth", authRouter);

  app.use(authenticate);
  app.use("/v1/subscription", subscriptionRouter);
  app.use(requireActiveSubscription);
  app.use("/v1/projects", projectsRouter);
  app.use("/v1/invitations", invitationsRouter);
  app.use("/v1/members", membersRouter);
  app.use("/v1", depositDelegatesRouter);
  app.use("/v1", memberDocumentsRouter);
  app.use("/v1/memberships", membershipsRouter);
  app.use("/v1/schedules", schedulesRouter);
  app.use("/v1/recurring-schedules", recurringSchedulesRouter);
  app.use("/v1", duesRouter);
  app.use("/v1/deposits", depositsRouter);
  app.use("/v1/uploads", uploadsRouter);
  app.use("/v1", receiptsRouter);
  app.use("/v1/expenses", expensesRouter);
  app.use("/v1/expense-categories", expenseCategoriesRouter);
  app.use("/v1/vendors", vendorsRouter);
  app.use("/v1/accounts", accountsRouter);
  app.use("/v1/incomes", incomesRouter);
  app.use("/v1/inventory-categories", inventoryCategoriesRouter);
  app.use("/v1/inventory", inventoryRouter);
  app.use("/v1/purchases", purchasesRouter);
  app.use("/v1/sales", salesRouter);
  app.use("/v1/transfers", transfersRouter);
  app.use("/v1", dashboardRouter);
  app.use("/v1", activityRouter);
  app.use("/v1", penaltiesRouter);
}
